### ISSUE TITLE
如何保证id连续

### ISSUE THREAD

**Issue by leitiannet** [flike/idgo#12]
----当ID生成器服务崩溃后,可以继续生成有效ID,避免了ID回绕的风险。
如果idgo突然崩溃了，之前批量生成的id会丢失吧，如何保证id连续呢？

**Comment by flike** [comment]
会丢失，然后重新获取一批id，这一批id肯定比之前的大。保证了递增，但不能保证连续

**Comment by leitiannet** [comment]
对id是一种浪费，是否考虑保证连续性呢？

**Comment by flike** [comment]
也谈不上浪费，比较idgo崩溃的概率非常低。你用int64计数，一次批量获取10000个id，还好吧。
