### ISSUE TITLE
make报错，谢谢

### ISSUE THREAD

**Issue by honor100** [flike/idgo#14]
make
go install ./...
config/config.go:6:2: cannot find package "github.com/BurntSushi/toml" in any of:
	/usr/local/go/src/github.com/BurntSushi/toml (from $GOROOT)
	/usr/local/src/github.com/BurntSushi/toml (from $GOPATH)
cmd/idgo/main.go:13:2: cannot find package "github.com/flike/golog" in any of:
	/usr/local/go/src/github.com/flike/golog (from $GOROOT)
	/usr/local/src/github.com/flike/golog (from $GOPATH)
server/idgo.go:8:2: cannot find package "github.com/go-sql-driver/mysql" in any of:
	/usr/local/go/src/github.com/go-sql-driver/mysql (from $GOROOT)
	/usr/local/src/github.com/go-sql-driver/mysql (from $GOPATH)
make: *** [build] Error 1

**Comment by flike** [comment]
需要按照godep

**Comment by honor100** [comment]
你好，按照文档执行了  go get github.com/tools/godep

**Comment by flike** [comment]
还是不行？

**Comment by honor100** [comment]
不行啊

**Comment by flike** [comment]
我周末抽空搞一下。

**Comment by honor100** [comment]
感谢，您先忙。
