### ISSUE TITLE
jedis客户端测试每秒只能产生7754个id

### ISSUE THREAD

**Issue by nuccch** [flike/idgo#5]
根据官方文档描述，每秒可生成大约20w个id。
通过java redis客户端jedis进行测试，每秒平均只能生成7754个id。测试代码如下：

// 通过java redis客户端测试idgo每秒生成id数
public class JRedisUtil {
	private static JRedisUtil instance = new JRedisUtil();
	private Jedis jedis = null;
	
	{
		String host = "127.0.0.1";
		int port = 6389;
		jedis = new Jedis(host, port);
	}
	
	public String get(String key) {
		return jedis.get(key);
	}
	
	public void set(String key, String value) {
		jedis.set(key, value);
	}

	private JRedisUtil() {
	}

	public static JRedisUtil getInstance() {
		return instance;
	}

	public static void main(String[] args) {
		JRedisUtil util = JRedisUtil.getInstance();
		long i = 1;
		long start = System.currentTimeMillis();
		for(i=1;;i++) {
			String value = util.get("abc");
			System.out.println(value);
			long end = System.currentTimeMillis();
			long interval = end - start;
			if(interval >= 1000) {
				break;
			}
		}
		System.out.println("Done!");
		System.out.println("i = " + i);
		// total: 7787 7960 8452 6974 6907 6748 8017 8164 8272 8266 // 共测试10次
		//   avg: 7754.7 // 平均每秒生成id数
	}

}

**Comment by flike** [comment]
我之前是本机连本机测试的，提高qps可以尝试改一下批量获取id的大小。
把https://github.com/flike/idgo/blob/792544f412569c803305a707c8367a5ebdb7e0b4/server/idgo.go文件中的BatchCount = 2000，改成20000试试？

**Comment by nuccch** [comment]
修改BatchCount值之后重新make测试，没有明显改善。
测试结果如下：
// total: 7787 7960 8452 6974 6907 6748 8017 8164 8272 8266
//   avg: **7754.7**
		
// 修改批量获取id参数BatchCount值后测试: 20000
// total: 8140 8219 8637 7951 8198 8220 8163 8896 7942 8902
//   avg: **8317.8**
// 没有明显改善
		
// 修改修改批量获取id参数BatchCount值后测试: 200000
// total: 8384 7352 8639 6765 8953 8793 7972 8411 8295 9267
//   avg: **8283.1**

修改idgo.go文件中的BatchCount值：
const (
	//create key table
	CreateTableSQLFormat = `
	CREATE TABLE %s (
    id bigint(20) unsigned NOT NULL auto_increment,
    PRIMARY KEY  (id)
) ENGINE=Innodb DEFAULT CHARSET=utf8 `

	//create key table if not exist
	CreateTableNTSQLFormat = `
	CREATE TABLE IF NOT EXISTS %s (
    id bigint(20) unsigned NOT NULL auto_increment,
    PRIMARY KEY  (id)
) ENGINE=Innodb DEFAULT CHARSET=utf8 `

	DropTableSQLFormat   = `DROP TABLE IF EXISTS %s`
	InsertIdSQLFormat    = "INSERT INTO %s(id) VALUES(%d)"
	SelectForUpdate      = "SELECT id FROM %s FOR UPDATE"
	UpdateIdSQLFormat    = "UPDATE %s SET id = id + %d"
	GetRowCountSQLFormat = "SELECT count(*) FROM %s"
	GetKeySQLFormat      = "show tables like '%s'"

	**BatchCount = 200000**
)

**Comment by flike** [comment]
是不是已经达到单线程上限了，改多线程试试？

**Comment by nuccch** [comment]
多线程测试跟单线程测试数据相差不多。
测试代码及结果如下：

private void mutiThreadTest() {
	long start = System.currentTimeMillis();
	for(int i = 0; i<10; i++) { // 同时启动10个线程测试，输出每个线程内获取到的id数
		new Thread(new RedisThread(start)).start();
	}
}
	
private class RedisThread implements Runnable {
	private long count = 1; // 线程计数
	private long start = 0;
		
	public RedisThread(long start) {
		this.start = start;
	}

	public void run() {
		for(;;) {
			long now = System.currentTimeMillis();
			long interval = now - start;
			if(interval >= 1000) {
				System.out.println("Done: " + Thread.currentThread().getId() + ", count = " + count);
				break;
			}
			Jedis jedis = new Jedis(host, port);
			String value = jedis.get("abc");
			//System.out.println(value);
			try {
				count++;
			} catch (Exception e) {
				e.printStackTrace();
			} finally {
				jedis.close();
			}
		}
	}
}

测试结果，分别输出10个线程内获取到的id数：
Thread: 10, count = 699
Thread: 9, count = 729
Thread: 16, count = 708
Thread: 15, count = 692
Thread: 17, count = 684
Thread: 11, count = 698
Thread: 12, count = 674
Thread: 13, count = 660
Thread: 18, count = 686
Thread: 14, count = 693

10个线程获取到的id总数与单线程获取到的id数相差不多。

**Comment by flike** [comment]
MySQL server和idgo是不是在一台机器上，要不然会跨网络，性能可能会有问题。

**Comment by nuccch** [comment]
MySQL和idgo都是在同一台机器，java代码也是在同一台机器。都是在本地测试的。

**Comment by flike** [comment]
你可以在idgo的关键地方打印一下log，看看耗时主要在哪个地方，代码比较简单，一看就懂 ：）
